{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "actual-budget.fullname" . }}
  labels:
    {{- include "actual-budget.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - secretName: {{ .Values.ingress.tls.secretName }} 
      hosts:
      - {{ trimPrefix "https://" .Values.ingress.url }}
  {{- end }}
  rules:
  - host: {{ trimPrefix "https://" .Values.ingress.url }}
    http:
      paths:
      - path: '/'
        pathType: Prefix
        backend:
          service:
            name: {{ include "actual-budget.fullname" . }}
            port:
              number: {{ .Values.service.port }}
  {{- end -}}

